### ISSUE TITLE
Prevent non-logged in users from accessing the API, except the login route.

### ISSUE THREAD

**Issue by steph-koopmanschap** [Nerds-Who-Code/Mental-Health-Tracker#35]
If a user is NOT logged in. The user should have no access to any of the API functions or routes except the one to log in a user.

This is to prevent unauthorized access to sensitive data of the users and the database.

If an unauthorized logged out user tries to connect to any of the api routes (except the login one) then the server should send a 401 Unauthorized response.

**Comment by ooddaa** [comment]
One of the ways it could be done is by adding an ```auth``` middleware to route handlers. 

[Here's an example](https://github.com/ooddaa/devconnect/blob/main/middleware/auth.js) which uses [JWT](https://jwt.io/) to authenticate users. 

[Here](https://github.com/ooddaa/devconnect/blob/main/routes/api/auth.js) is how the auth middleware it is imported and used in route handlers.

**Comment by steph-koopmanschap** [comment]
What does this do? or where does it come from?
`const config = require('config');`
in your examples.

Does anything need to be done on the client side?

**Comment by ooddaa** [comment]
> What does this do? or where does it come from?
> `const config = require('config');`
> in your examples.

[Config](https://www.npmjs.com/package/config) package allows configuring Nodejs environments. At the moment we have not bothered with setting up separate development/testing/production environments but in future we'll have to do it. Config files (.json) should not be public as they contain secrets. Normally configuration .json files are either added to .gitignore or encrypted with [git-crypt](https://github.com/node-config/node-config/wiki/Securing-Production-Config-Files).

> And is the jwtSecret auto-generated?  Or can you make it anything you want?

It's not auto-generated, you should set up your own JWT secret.

> If the project is open-source and the jwtSecret secret is visible in the code?  Then is possible for anyone to use the secret key without actually logging in? 

Secrets should not be publicly available (I just didn't care for that project and pushed all to github). 

> Or should the secret key be hashed first and the plaintext key be shared by server owners?

More robust would be to use [git-crypt](https://github.com/node-config/node-config/wiki/Securing-Production-Config-Files) to encrypt config files for those who are not authorized to see them. Then encrypted files can be added to git and versioned. You and I would need to exchange public keys.

> Does anything need to be done on the client side?

JWT-based authentication works as follows: 

1. Server receives credentials and checks them. If they are valid, it creates (signs) and returns a JWT token (with expiration/no expiration) ([at registration](https://github.com/ooddaa/devconnect/blob/d376b4565e76297e06a67325e4138d8c3e472471/routes/api/users.js#L72-L87)) or ([at authorization](https://github.com/ooddaa/devconnect/blob/d376b4565e76297e06a67325e4138d8c3e472471/routes/api/auth.js#L52-L62)).
2. Client stores JWT in localStorage and adds it to every request it makes to the server. "Adds to every request" means client sets [JWT as 'x-auth-token' header](https://github.com/ooddaa/devconnect/blob/d376b4565e76297e06a67325e4138d8c3e472471/middleware/auth.js#L7), because that is where server expects to find JWT before deciding to grant/deny access to protected routes (which are all but /auth and /register).
