### ISSUE TITLE
Unable to login and register

### ISSUE THREAD

**Issue by nab-sa** [Nerds-Who-Code/Mental-Health-Tracker#50]
**Describe the bug**
When trying to login or register an alert message pop-up saying the **"password or username is wrong"** or when submitting the form that **"something went wrong while creating your account"**.

**To Reproduce**
I just execute the `npm start` command 

**Additional context**
I have an alert pop-up that says the registration was successful on Ubuntu but I still cannot login and when trying to register again it doesn't work anymore, plus the output message on the terminal when I execute `npm start` change depending on the OS I use (although they are potentially the same error):

**Windows 10:**
![This is an image](https://i.imgur.com/654OCp8.png)

Error message on the console DevTools:
![This is an image](https://i.imgur.com/lDUm9Ah.png)

**Ubuntu 22.04:**
![This is an image](https://i.imgur.com/CyoSVKF.png)

Error message on the console DevTools:
![This is an image](https://i.imgur.com/9Njc3Mh.png)

**Comment by steph-koopmanschap** [comment]
I am not sure where the login error comes from. Logging in on the elderGnome account works for me. 
Are you sure you used the correct username and password:
**Username:** elderGnome
**Password:** HAHAHAHA

Have you tried other accounts? Does the error show up on every acount or just the elderGnome account?
Have you tried **username**: test123 **password**: test

I believe the second error is normal, because you can not create an account that already exists.
I created an account and it worked for me. (one that does not exist yet)
If you create a new non-existing account does the error still show up?

**Comment by nab-sa** [comment]
> Are you sure you used the correct username and password:

Yes I am sure.

> Have you tried other accounts? Does the error show up on every acount or just the elderGnome account?

I tried several account and it never worked

> Have you tried username: test123 password: test

Doesn't work

> I created an account and it worked for me. (one that does not exist yet) 
If you create a new non-existing account does the error still show up?

It actually worked ! (But only on Ubuntu)

**Comment by xintamosaik** [comment]
I still have this bug. Can not create an account.

**Comment by xintamosaik** [comment]
Seems to be old news? Closing issues if you do not veto against it

**Comment by nab-sa** [comment]
Heyo ! I'm back 
I checked recently and the problem was back I'll test again more thoroughly tomorrow.
(If I'm the only one with this problem it's most likely a problem on my end )

**Comment by xintamosaik** [comment]
Great, that's good now then!
